"""add ssh_keys description

Revision ID: 2644b6018b5d
Revises: a4ed84b786f2
Create Date: 2026-07-22 23:35:33.746764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2644b6018b5d'
down_revision = 'a4ed84b786f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate также обнаружил pre-existing drift, не относящийся к A2
    # (server_categories/server_category_association, logs.timestamp type) —
    # оставлен нетронутым, здесь не включён. ssh_keys.description добавляется,
    # т.к. load-bearing для E3 (/api/svc/keys/generate — "имя человека в
    # name/description", §4.3 п.2 архитектуры) и без миграции колонки не будет
    # ни в одном окружении, поднятом через `flask db upgrade`.
    # Идемпотентно: на проде ssh_keys.description УЖЕ есть (drift) — иначе
    # duplicate column и деплой падает. Проверяем перед add_column.
    insp = sa.inspect(op.get_bind())
    columns = {c["name"] for c in insp.get_columns("ssh_keys")}
    if 'description' in columns:
        return
    with op.batch_alter_table('ssh_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    insp = sa.inspect(op.get_bind())
    columns = {c["name"] for c in insp.get_columns("ssh_keys")}
    if 'description' not in columns:
        return
    with op.batch_alter_table('ssh_keys', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
