"""Fresh start with adaptive SSH support

Revision ID: 878d8d07c660
Revises: 
Create Date: 2025-11-05 12:57:49.949377

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "878d8d07c660"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("target", sa.String(length=100), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ssh_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("private_key_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("fingerprint", sa.String(length=100), nullable=False),
        sa.Column("key_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint"),
    )
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("ssh_port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_check", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("openssh_version", sa.String(length=20), nullable=True),
        sa.Column("requires_legacy_ssh", sa.Boolean(), nullable=False),
        sa.Column("access_key_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["access_key_id"],
            ["ssh_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "key_deployments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ssh_key_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column(
            "deployed_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deployed_by", sa.Integer(), nullable=False),
        sa.Column("revoked_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("revoked_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deployed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ssh_key_id"], ["ssh_keys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("key_deployments", schema=None) as batch_op:
        batch_op.create_index(
            "idx_key_server_revoked", ["ssh_key_id", "server_id", "revoked_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_key_deployments_deployed_at"), ["deployed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_key_deployments_revoked_at"), ["revoked_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_key_deployments_server_id"), ["server_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_key_deployments_ssh_key_id"), ["ssh_key_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("key_deployments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_key_deployments_ssh_key_id"))
        batch_op.drop_index(batch_op.f("ix_key_deployments_server_id"))
        batch_op.drop_index(batch_op.f("ix_key_deployments_revoked_at"))
        batch_op.drop_index(batch_op.f("ix_key_deployments_deployed_at"))
        batch_op.drop_index("idx_key_server_revoked")

    op.drop_table("key_deployments")
    op.drop_table("servers")
    op.drop_table("ssh_keys")
    op.drop_table("logs")
    op.drop_table("users")
    # ### end Alembic commands ###
