"""add bootstrap_request_id

Revision ID: a4ed84b786f2
Revises: 878d8d07c660
Create Date: 2026-07-22 23:13:34.033375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ed84b786f2'
down_revision = '878d8d07c660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also detected pre-existing drift unrelated to this task
    # (server_categories/server_category_association tables, ssh_keys.description,
    # logs.timestamp type) — out of scope for A2, left untouched, not included here.
    # Идемпотентно: колонка/индекс могли уже существовать (drift на проде).
    insp = sa.inspect(op.get_bind())
    columns = {c["name"] for c in insp.get_columns("servers")}
    indexes = {ix["name"] for ix in insp.get_indexes("servers")}
    need_col = 'bootstrap_request_id' not in columns
    need_ix = 'ix_servers_bootstrap_request_id' not in indexes
    if not (need_col or need_ix):
        return
    with op.batch_alter_table('servers', schema=None) as batch_op:
        if need_col:
            batch_op.add_column(sa.Column('bootstrap_request_id', sa.String(length=64), nullable=True))
        if need_ix:
            batch_op.create_index(batch_op.f('ix_servers_bootstrap_request_id'), ['bootstrap_request_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    insp = sa.inspect(op.get_bind())
    columns = {c["name"] for c in insp.get_columns("servers")}
    if 'bootstrap_request_id' not in columns:
        return
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_bootstrap_request_id'))
        batch_op.drop_column('bootstrap_request_id')

    # ### end Alembic commands ###
